# Generated by Django 2.2 on 2021-04-27 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure_app', '0003_auto_20210426_0013'),
        ('adventure_app', '0003_auto_20210426_2108'),
    ]

    operations = [
    ]
