# Generated by Django 2.2 on 2021-05-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure_app', '0004_merge_20210427_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='visitor', max_length=20),
        ),
    ]
