# Generated by Django 3.2.4 on 2021-06-13 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure_app', '0006_auto_20210611_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.TextField()),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_posts', to='adventure_app.adventure')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_posts', to='adventure_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField()),
                ('discussion_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='adventure_app.discussionpost')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_replies', to='adventure_app.user')),
            ],
        ),
    ]
